import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import SideMenu from './SideMenu'
import { Toaster } from "@/components/ui/toaster"
import { getServerSession } from 'next-auth'
import LoginForm from '@/components/LoginForm'
import { AuthProvider } from './providers/auth-provider'
import RotaProtegida from './RotaProtegida'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();

  return (
    <AuthProvider>
      <html lang="en" className={inter.className}>
        <body className='max-h-screen bg-slate-400 '>
          <NavBar />
          <RotaProtegida>
            {session ?
              <main className='flex '>
                <SideMenu />
                <div className="container ml-[16.7%] h-screen pb-4 pt-14 py-4">
                  {children}
                  <Toaster />
                </div>
              </main>
              :
              <LoginForm />
            }
          </RotaProtegida>

        </body>
      </html>
    </AuthProvider>
  )
}
