import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import SideMenu from './SideMenu'
import { Toaster } from "@/components/ui/toaster"
import { getServerSession } from 'next-auth'
import LoginForm from '@/components/LoginForm'
import { AuthProvider } from './providers/auth-provider'
import RotaProtegida from './RotaProtegida'
import MobileNav from '@/components/Responsivo/Menubar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();

  return (
    <AuthProvider>
      <html lang="en" className={inter.className}>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          </meta>
        </head>
        <body className='max-h-screen max-w-full w-full  bg-slate-400'>
          <NavBar />
          <RotaProtegida>
            {session ?
              <main className='flex '>
                <div className="hidden lg:flex flex-start pt-14 px-4">
                  <SideMenu />
                </div>
                <div className="lg:container w-full lg:ml-[16.7%] pb-4 pt-14">
                  {children}
                  <Toaster />
                </div>
              </main>
              :
              <LoginForm />
            }
          </RotaProtegida>
        </body>
      </html>
    </AuthProvider>
  )
}
